/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ConnectionRouteImport } from './routes/connection'
import { Route as HomeRouteImport } from './routes/home'
import { Route as SupportRouteImport } from './routes/support'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityActivityRouteImport } from './routes/community.$activity'
import { Route as ConnectionIndexRouteImport } from './routes/connection.index'
import { Route as ConnectionOptionRouteImport } from './routes/connection.$option'
import { Route as NeedCategoryRouteImport } from './routes/need.$category'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as SupportOptionRouteImport } from './routes/support.$option'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionRoute = ConnectionRouteImport.update({
  id: '/connection',
  path: '/connection',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityActivityRoute = CommunityActivityRouteImport.update({
  id: '/$activity',
  path: '/$activity',
  getParentRoute: () => CommunityRoute,
} as any)
const ConnectionIndexRoute = ConnectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectionRoute,
} as any)
const ConnectionOptionRoute = ConnectionOptionRouteImport.update({
  id: '/$option',
  path: '/$option',
  getParentRoute: () => ConnectionRoute,
} as any)
const NeedCategoryRoute = NeedCategoryRouteImport.update({
  id: '/need/$category',
  path: '/need/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportRoute,
} as any)
const SupportOptionRoute = SupportOptionRouteImport.update({
  id: '/$option',
  path: '/$option',
  getParentRoute: () => SupportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRouteWithChildren
  '/connection': typeof ConnectionRouteWithChildren
  '/home': typeof HomeRoute
  '/support': typeof SupportRouteWithChildren
  '/community/$activity': typeof CommunityActivityRoute
  '/connection/$option': typeof ConnectionOptionRoute
  '/need/$category': typeof NeedCategoryRoute
  '/support/$option': typeof SupportOptionRoute
  '/community/': typeof CommunityIndexRoute
  '/connection/': typeof ConnectionIndexRoute
  '/support/': typeof SupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/community/$activity': typeof CommunityActivityRoute
  '/connection/$option': typeof ConnectionOptionRoute
  '/need/$category': typeof NeedCategoryRoute
  '/support/$option': typeof SupportOptionRoute
  '/community': typeof CommunityIndexRoute
  '/connection': typeof ConnectionIndexRoute
  '/support': typeof SupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRouteWithChildren
  '/connection': typeof ConnectionRouteWithChildren
  '/home': typeof HomeRoute
  '/support': typeof SupportRouteWithChildren
  '/community/$activity': typeof CommunityActivityRoute
  '/connection/$option': typeof ConnectionOptionRoute
  '/need/$category': typeof NeedCategoryRoute
  '/support/$option': typeof SupportOptionRoute
  '/community/': typeof CommunityIndexRoute
  '/connection/': typeof ConnectionIndexRoute
  '/support/': typeof SupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/connection'
    | '/home'
    | '/support'
    | '/community/$activity'
    | '/connection/$option'
    | '/need/$category'
    | '/support/$option'
    | '/community/'
    | '/connection/'
    | '/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/community/$activity'
    | '/connection/$option'
    | '/need/$category'
    | '/support/$option'
    | '/community'
    | '/connection'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/connection'
    | '/home'
    | '/support'
    | '/community/$activity'
    | '/connection/$option'
    | '/need/$category'
    | '/support/$option'
    | '/community/'
    | '/connection/'
    | '/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  ConnectionRoute: typeof ConnectionRouteWithChildren
  HomeRoute: typeof HomeRoute
  SupportRoute: typeof SupportRouteWithChildren
  NeedCategoryRoute: typeof NeedCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection': {
      id: '/connection'
      path: '/connection'
      fullPath: '/connection'
      preLoaderRoute: typeof ConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/$activity': {
      id: '/community/$activity'
      path: '/$activity'
      fullPath: '/community/$activity'
      preLoaderRoute: typeof CommunityActivityRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/connection/': {
      id: '/connection/'
      path: '/'
      fullPath: '/connection/'
      preLoaderRoute: typeof ConnectionIndexRouteImport
      parentRoute: typeof ConnectionRoute
    }
    '/connection/$option': {
      id: '/connection/$option'
      path: '/$option'
      fullPath: '/connection/$option'
      preLoaderRoute: typeof ConnectionOptionRouteImport
      parentRoute: typeof ConnectionRoute
    }
    '/need/$category': {
      id: '/need/$category'
      path: '/need/$category'
      fullPath: '/need/$category'
      preLoaderRoute: typeof NeedCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/$option': {
      id: '/support/$option'
      path: '/$option'
      fullPath: '/support/$option'
      preLoaderRoute: typeof SupportOptionRouteImport
      parentRoute: typeof SupportRoute
    }
  }
}

interface CommunityRouteChildren {
  CommunityActivityRoute: typeof CommunityActivityRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityActivityRoute: CommunityActivityRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface ConnectionRouteChildren {
  ConnectionOptionRoute: typeof ConnectionOptionRoute
  ConnectionIndexRoute: typeof ConnectionIndexRoute
}

const ConnectionRouteChildren: ConnectionRouteChildren = {
  ConnectionOptionRoute: ConnectionOptionRoute,
  ConnectionIndexRoute: ConnectionIndexRoute,
}

const ConnectionRouteWithChildren = ConnectionRoute._addFileChildren(
  ConnectionRouteChildren,
)

interface SupportRouteChildren {
  SupportOptionRoute: typeof SupportOptionRoute
  SupportIndexRoute: typeof SupportIndexRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportOptionRoute: SupportOptionRoute,
  SupportIndexRoute: SupportIndexRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRouteWithChildren,
  ConnectionRoute: ConnectionRouteWithChildren,
  HomeRoute: HomeRoute,
  SupportRoute: SupportRouteWithChildren,
  NeedCategoryRoute: NeedCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
